### ISSUE TITLE
FAUST_DATA_with_GIH

### ISSUE THREAD

**Issue by ykasten** [mikecheninoulu/Unsupervised_IEPGAN#4]
I could not understand how to get the data that FAUST_DATA_with_GIH requires. 

Specifically, it searches for obj files:  pose_mesh_path = self.path+'tr_reg_'+str(pose_mesh_idx).zfill(3)+'.obj'. However, the FAUST dataset supplies ply files with this prefix (e.g. tr_scan_030.ply). 

Furthermore,   gt_path = self.path_GIH_gt+'tr_reg_'+str(identity_mesh_idx).zfill(3)+'.pkl' expects pkl file which I can't understand how to produce.  The LIMP repository produces folders (not pkl files) with this prefix e.g. tr_reg_099_2000. Each folder contains two files: 1. mesh.triv, 2. mesh.vert.

Can you please explain how to get the pkl and obj files? 
Alternatively, I read in another issue that you planned to upload the preprocessed data to the cloud 3 months ago. Would it be possible for you to upload the data? 

Thanks, 
Yoni

**Comment by mikecheninoulu** [comment]
Hi, thanks for being interested in our work.

Since I need to run my code on the server, some libraries to load the .ply file like pyrender is not compilable, I had to convert all the files into .obj  format for trimesh to process (way faster).

I generated the GIH myself and save it as .pkl file (again, for fast processing), instead of using the LIMP one. Also, LIMP downsampled the meshes into 2100 vertices while I calculated 6890 vertices, the GIH sizes are different. 

Please check the script I newly attached (in the GIH calculating folder) to see how to generate the GIH maps.

Preprocessed data is uploaded and you can download it now, sorry that it takes longer than expected due to my procrastination.

**Comment by ykasten** [comment]
Thank you very much!

**Comment by mikecheninoulu** [comment]
> Thank you very much!

Welcome! Looking forward to having further research cooperation!
